import { Colors } from "../../../types/global";

const Filled: Record<Colors, Record<string, string>> = {
    amber: {
        backgroud: "bg-amber-500",
        border: "border-amber-500",
        color: "text-white",
        shadow: "shadow-md shadow-amber-500/20",
        hover: "hover:shadow-lg hover:shadow-amber-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    blue: {
        backgroud: "bg-blue-500",
        border: "border-blue-500",
        color: "text-white",
        shadow: "shadow-md shadow-blue-500/20",
        hover: "hover:shadow-lg hover:shadow-blue-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    cyan: {
        backgroud: "bg-cyan-500",
        border: "border-cyan-500",
        color: "text-white",
        shadow: "shadow-md shadow-cyan-500/20",
        hover: "hover:shadow-lg hover:shadow-cyan-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    emerald: {
        backgroud: "bg-emerald-500",
        border: "border-emerald-500",
        color: "text-white",
        shadow: "shadow-md shadow-emerald-500/20",
        hover: "hover:shadow-lg hover:shadow-emerald-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    fuchsia: {
        backgroud: "bg-fuchsia-500",
        border: "border-fuchsia-500",
        color: "text-white",
        shadow: "shadow-md shadow-fuchsia-500/20",
        hover: "hover:shadow-lg hover:shadow-fuchsia-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    gray: {
        backgroud: "bg-gray-500",
        border: "border-gray-500",
        color: "text-white",
        shadow: "shadow-md shadow-gray-500/20",
        hover: "hover:shadow-lg hover:shadow-gray-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    green: {
        backgroud: "bg-green-500",
        border: "border-green-500",
        color: "text-white",
        shadow: "shadow-md shadow-green-500/20",
        hover: "hover:shadow-lg hover:shadow-green-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    indigo: {
        backgroud: "bg-indigo-500",
        border: "border-indigo-500",
        color: "text-white",
        shadow: "shadow-md shadow-indigo-500/20",
        hover: "hover:shadow-lg hover:shadow-indigo-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    lime: {
        backgroud: "bg-lime-500",
        border: "border-lime-500",
        color: "text-white",
        shadow: "shadow-md shadow-lime-500/20",
        hover: "hover:shadow-lg hover:shadow-lime-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    neutral: {
        backgroud: "bg-neutral-500",
        border: "border-neutral-500",
        color: "text-white",
        shadow: "shadow-md shadow-neutral-500/20",
        hover: "hover:shadow-lg hover:shadow-neutral-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    orange: {
        backgroud: "bg-orange-500",
        border: "border-orange-500",
        color: "text-white",
        shadow: "shadow-md shadow-orange-500/20",
        hover: "hover:shadow-lg hover:shadow-orange-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    pink: {
        backgroud: "bg-pink-500",
        border: "border-pink-500",
        color: "text-white",
        shadow: "shadow-md shadow-pink-500/20",
        hover: "hover:shadow-lg hover:shadow-pink-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    purple: {
        backgroud: "bg-purple-500",
        border: "border-purple-500",
        color: "text-white",
        shadow: "shadow-md shadow-purple-500/20",
        hover: "hover:shadow-lg hover:shadow-purple-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    red: {
        backgroud: "bg-red-500",
        border: "border-red-500",
        color: "text-white",
        shadow: "shadow-md shadow-red-500/20",
        hover: "hover:shadow-lg hover:shadow-red-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    rose: {
        backgroud: "bg-rose-500",
        border: "border-rose-500",
        color: "text-white",
        shadow: "shadow-md shadow-rose-500/20",
        hover: "hover:shadow-lg hover:shadow-rose-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    sky: {
        backgroud: "bg-sky-500",
        border: "border-sky-500",
        color: "text-white",
        shadow: "shadow-md shadow-sky-500/20",
        hover: "hover:shadow-lg hover:shadow-sky-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    slate: {
        backgroud: "bg-slate-500",
        border: "border-slate-500",
        color: "text-white",
        shadow: "shadow-md shadow-slate-500/20",
        hover: "hover:shadow-lg hover:shadow-slate-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    stone: {
        backgroud: "bg-stone-500",
        border: "border-stone-500",
        color: "text-white",
        shadow: "shadow-md shadow-stone-500/20",
        hover: "hover:shadow-lg hover:shadow-stone-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    teal: {
        backgroud: "bg-teal-500",
        border: "border-teal-500",
        color: "text-white",
        shadow: "shadow-md shadow-teal-500/20",
        hover: "hover:shadow-lg hover:shadow-teal-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    violet: {
        backgroud: "bg-violet-500",
        border: "border-violet-500",
        color: "text-white",
        shadow: "shadow-md shadow-violet-500/20",
        hover: "hover:shadow-lg hover:shadow-violet-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    yellow: {
        backgroud: "bg-yellow-500",
        border: "border-yellow-500",
        color: "text-white",
        shadow: "shadow-md shadow-yellow-500/20",
        hover: "hover:shadow-lg hover:shadow-yellow-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    zinc: {
        backgroud: "bg-zinc-500",
        border: "border-zinc-500",
        color: "text-white",
        shadow: "shadow-md shadow-zinc-500/20",
        hover: "hover:shadow-lg hover:shadow-zinc-500/40",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
};

export default Filled;
