import { TColors } from "~types/global";

const OutlinedFilled: Record<TColors, Record<string, string>> = {
    primary: {
        border: "border border-primary-500",
        color: "text-primary-500",
        hover: "hover:bg-primary-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    secondary: {
        border: "border border-secondary-500",
        color: "text-secondary-500",
        hover: "hover:bg-secondary-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    tertiary: {
        border: "border border-tertiary-500",
        color: "text-tertiary-500",
        hover: "hover:bg-tertiary-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    amber: {
        border: "border border-amber-500",
        color: "text-amber-500",
        hover: "hover:bg-amber-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    blue: {
        border: "border border-blue-500",
        color: "text-blue-500",
        hover: "hover:bg-blue-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    cyan: {
        border: "border border-cyan-500",
        color: "text-cyan-500",
        hover: "hover:bg-cyan-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    emerald: {
        border: "border border-emerald-500",
        color: "text-emerald-500",
        hover: "hover:bg-emerald-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    fuchsia: {
        border: "border border-fuchsia-500",
        color: "text-fuchsia-500",
        hover: "hover:bg-fuchsia-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    gray: {
        border: "border border-gray-500",
        color: "text-gray-500",
        hover: "hover:bg-gray-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    green: {
        border: "border border-green-500",
        color: "text-green-500",
        hover: "hover:bg-green-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    indigo: {
        border: "border border-indigo-500",
        color: "text-indigo-500",
        hover: "hover:bg-indigo-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    lime: {
        border: "border border-lime-500",
        color: "text-lime-500",
        hover: "hover:bg-lime-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    neutral: {
        border: "border border-neutral-500",
        color: "text-neutral-500",
        hover: "hover:bg-neutral-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    orange: {
        border: "border border-orange-500",
        color: "text-orange-500",
        hover: "hover:bg-orange-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    pink: {
        border: "border border-pink-500",
        color: "text-pink-500",
        hover: "hover:bg-pink-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    purple: {
        border: "border border-purple-500",
        color: "text-purple-500",
        hover: "hover:bg-purple-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    red: {
        border: "border border-red-500",
        color: "text-red-500",
        hover: "hover:bg-red-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    rose: {
        border: "border border-rose-500",
        color: "text-rose-500",
        hover: "hover:bg-rose-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    sky: {
        border: "border border-sky-500",
        color: "text-sky-500",
        hover: "hover:bg-sky-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    slate: {
        border: "border border-slate-500",
        color: "text-slate-500",
        hover: "hover:bg-slate-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    stone: {
        border: "border border-stone-500",
        color: "text-stone-500",
        hover: "hover:bg-stone-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    teal: {
        border: "border border-teal-500",
        color: "text-teal-500",
        hover: "hover:bg-teal-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    violet: {
        border: "border border-violet-500",
        color: "text-violet-500",
        hover: "hover:bg-violet-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    yellow: {
        border: "border border-yellow-500",
        color: "text-yellow-500",
        hover: "hover:bg-yellow-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    zinc: {
        border: "border border-zinc-500",
        color: "text-zinc-500",
        hover: "hover:bg-zinc-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
};

export default OutlinedFilled;
