import { Colors } from "../../../types/global";

const Outlined: Record<Colors, Record<string, string>> = {
    primary: {
        border: "border border-primary-500",
        color: "text-primary-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-primary-200",
        active: "active:opacity-[0.85]",
    },
    secondary: {
        border: "border border-secondary-500",
        color: "text-secondary-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-secondary-200",
        active: "active:opacity-[0.85]",
    },
    tertiary: {
        border: "border border-tertiary-500",
        color: "text-tertiary-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-tertiary-200",
        active: "active:opacity-[0.85]",
    },
    amber: {
        border: "border border-amber-500",
        color: "text-amber-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-amber-200",
        active: "active:opacity-[0.85]",
    },
    blue: {
        border: "border border-blue-500",
        color: "text-blue-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-blue-200",
        active: "active:opacity-[0.85]",
    },
    cyan: {
        border: "border border-cyan-500",
        color: "text-cyan-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-cyan-200",
        active: "active:opacity-[0.85]",
    },
    emerald: {
        border: "border border-emerald-500",
        color: "text-emerald-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-emerald-200",
        active: "active:opacity-[0.85]",
    },
    fuchsia: {
        border: "border border-fuchsia-500",
        color: "text-fuchsia-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-fuchsia-200",
        active: "active:opacity-[0.85]",
    },
    gray: {
        border: "border border-gray-500",
        color: "text-gray-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-gray-200",
        active: "active:opacity-[0.85]",
    },
    green: {
        border: "border border-green-500",
        color: "text-green-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-green-200",
        active: "active:opacity-[0.85]",
    },
    indigo: {
        border: "border border-indigo-500",
        color: "text-indigo-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-indigo-200",
        active: "active:opacity-[0.85]",
    },
    lime: {
        border: "border border-lime-500",
        color: "text-lime-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-lime-200",
        active: "active:opacity-[0.85]",
    },
    neutral: {
        border: "border border-neutral-500",
        color: "text-neutral-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-neutral-200",
        active: "active:opacity-[0.85]",
    },
    orange: {
        border: "border border-orange-500",
        color: "text-orange-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-orange-200",
        active: "active:opacity-[0.85]",
    },
    pink: {
        border: "border border-pink-500",
        color: "text-pink-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-pink-200",
        active: "active:opacity-[0.85]",
    },
    purple: {
        border: "border border-purple-500",
        color: "text-purple-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-purple-200",
        active: "active:opacity-[0.85]",
    },
    red: {
        border: "border border-red-500",
        color: "text-red-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-red-200",
        active: "active:opacity-[0.85]",
    },
    rose: {
        border: "border border-rose-500",
        color: "text-rose-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-rose-200",
        active: "active:opacity-[0.85]",
    },
    sky: {
        border: "border border-sky-500",
        color: "text-sky-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-sky-200",
        active: "active:opacity-[0.85]",
    },
    slate: {
        border: "border border-slate-500",
        color: "text-slate-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-slate-200",
        active: "active:opacity-[0.85]",
    },
    stone: {
        border: "border border-stone-500",
        color: "text-stone-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-stone-200",
        active: "active:opacity-[0.85]",
    },
    teal: {
        border: "border border-teal-500",
        color: "text-teal-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-teal-200",
        active: "active:opacity-[0.85]",
    },
    violet: {
        border: "border border-violet-500",
        color: "text-violet-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-violet-200",
        active: "active:opacity-[0.85]",
    },
    yellow: {
        border: "border border-yellow-500",
        color: "text-yellow-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-yellow-200",
        active: "active:opacity-[0.85]",
    },
    zinc: {
        border: "border border-zinc-500",
        color: "text-zinc-500",
        hover: "hover:opacity-75",
        focus: "focus:ring focus:ring-zinc-200",
        active: "active:opacity-[0.85]",
    },
};

export default Outlined;
