import { Colors } from "../../../types/global";

const OutlinedFilled: Record<Colors, Record<string, string>> = {
    amber: {
        border: "border border-amber-500",
        color: "text-amber-500",
        hover: "hover:shadow-lg hover:shadow-amber-500/40 hover:bg-amber-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    blue: {
        border: "border border-blue-500",
        color: "text-blue-500",
        hover: "hover:shadow-lg hover:shadow-blue-500/40 hover:bg-blue-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    cyan: {
        border: "border border-cyan-500",
        color: "text-cyan-500",
        hover: "hover:shadow-lg hover:shadow-cyan-500/40 hover:bg-cyan-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    emerald: {
        border: "border border-emerald-500",
        color: "text-emerald-500",
        hover: "hover:shadow-lg hover:shadow-emerald-500/40 hover:bg-emerald-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    fuchsia: {
        border: "border border-fuchsia-500",
        color: "text-fuchsia-500",
        hover: "hover:shadow-lg hover:shadow-fuchsia-500/40 hover:bg-fuchsia-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    gray: {
        border: "border border-gray-500",
        color: "text-gray-500",
        hover: "hover:shadow-lg hover:shadow-gray-500/40 hover:bg-gray-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    green: {
        border: "border border-green-500",
        color: "text-green-500",
        hover: "hover:shadow-lg hover:shadow-green-500/40 hover:bg-green-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    indigo: {
        border: "border border-indigo-500",
        color: "text-indigo-500",
        hover: "hover:shadow-lg hover:shadow-indigo-500/40 hover:bg-indigo-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    lime: {
        border: "border border-lime-500",
        color: "text-lime-500",
        hover: "hover:shadow-lg hover:shadow-lime-500/40 hover:bg-lime-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    neutral: {
        border: "border border-neutral-500",
        color: "text-neutral-500",
        hover: "hover:shadow-lg hover:shadow-neutral-500/40 hover:bg-neutral-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    orange: {
        border: "border border-orange-500",
        color: "text-orange-500",
        hover: "hover:shadow-lg hover:shadow-orange-500/40 hover:bg-orange-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    pink: {
        border: "border border-pink-500",
        color: "text-pink-500",
        hover: "hover:shadow-lg hover:shadow-pink-500/40 hover:bg-pink-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    purple: {
        border: "border border-purple-500",
        color: "text-purple-500",
        hover: "hover:shadow-lg hover:shadow-purple-500/40 hover:bg-purple-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    red: {
        border: "border border-red-500",
        color: "text-red-500",
        hover: "hover:shadow-lg hover:shadow-red-500/40 hover:bg-red-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    rose: {
        border: "border border-rose-500",
        color: "text-rose-500",
        hover: "hover:shadow-lg hover:shadow-rose-500/40 hover:bg-rose-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    sky: {
        border: "border border-sky-500",
        color: "text-sky-500",
        hover: "hover:shadow-lg hover:shadow-sky-500/40 hover:bg-sky-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    slate: {
        border: "border border-slate-500",
        color: "text-slate-500",
        hover: "hover:shadow-lg hover:shadow-slate-500/40 hover:bg-slate-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    stone: {
        border: "border border-stone-500",
        color: "text-stone-500",
        hover: "hover:shadow-lg hover:shadow-stone-500/40 hover:bg-stone-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    teal: {
        border: "border border-teal-500",
        color: "text-teal-500",
        hover: "hover:shadow-lg hover:shadow-teal-500/40 hover:bg-teal-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    violet: {
        border: "border border-violet-500",
        color: "text-violet-500",
        hover: "hover:shadow-lg hover:shadow-violet-500/40 hover:bg-violet-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    yellow: {
        border: "border border-yellow-500",
        color: "text-yellow-500",
        hover: "hover:shadow-lg hover:shadow-yellow-500/40 hover:bg-yellow-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
    zinc: {
        border: "border border-zinc-500",
        color: "text-zinc-500",
        hover: "hover:shadow-lg hover:shadow-zinc-500/40 hover:bg-zinc-500 hover:text-white",
        focus: "focus:opacity-[0.85] focus:shadow-none",
        active: "active:opacity-[0.85] active:shadow-none",
    },
};

export default OutlinedFilled;
