import { Colors } from "../../../types/global";

const Default: Record<Colors, Record<string, string>> = {
    primary: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-primary-500",
    },
    secondary: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-secondary-500",
    },
    tertiary: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-tertiary-500",
    },
    amber: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-amber-500",
    },
    blue: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-blue-500",
    },
    cyan: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-cyan-500",
    },
    emerald: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-emerald-500",
    },
    fuchsia: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-fuchsia-500",
    },
    gray: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-gray-500",
    },
    green: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-green-500",
    },
    indigo: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-indigo-500",
    },
    lime: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-lime-500",
    },
    neutral: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-neutral-500",
    },
    orange: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-orange-500",
    },
    pink: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-pink-500",
    },
    purple: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-purple-500",
    },
    red: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-red-500",
    },
    rose: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-rose-500",
    },
    sky: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-sky-500",
    },
    slate: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-slate-500",
    },
    stone: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-stone-500",
    },
    teal: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-teal-500",
    },
    violet: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-violet-500",
    },
    yellow: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-yellow-500",
    },
    zinc: {
        backgorund: "bg-white",
        border: "border-gray-300",
        color: "text-gray-700",
        hover: "hover:border-gray-400",
        focus: "focus:border-zinc-500",
    },
};

export default Default;
